/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryStairsNew.glb -t -k -i -T 
Files: LibraryStairsNew.glb [208.63KB] > /home/tomoon/Documents/archiveOfBabel/public/models/LibraryStairsNew-transformed.glb [152.28KB] (27%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Box, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

type GLTFResult = GLTF & {
  nodes: {
    floor2: THREE.Mesh
    ramp: THREE.Mesh
    lightGem004: THREE.Mesh
    object1063: THREE.Mesh
    object2008: THREE.Mesh
    object1093: THREE.Mesh
    object1093_1: THREE.Mesh
    stairs: THREE.Mesh
  }
  materials: {
    fresnelGlow: THREE.MeshStandardMaterial
    ['floor.003']: THREE.MeshStandardMaterial
    ['oldwood.004']: THREE.MeshStandardMaterial
    Wall: THREE.MeshStandardMaterial
    sandTrim: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export const LibraryStairsNew = () => {
  const { nodes, materials } = useGLTF('/models/LibraryStairsNew-transformed.glb') as GLTFResult
  const { nodes: colliders,materials:colliderMat } = useGLTF('/models/LibraryStairsNewColliders-transformed.glb') as GLTFResult

  return (
    <group dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <Box scale={[2.1,2,1.1]} position={[-2.5,0,0]} />
      <mesh name="floor2" geometry={colliders.floor2.geometry} material={colliderMat.floor} position={[-1, 0.1, -1]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="ramp" geometry={colliders.ramp.geometry} material={'transparent'} position={[-2, -1.9, -1]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      </RigidBody>
      <mesh name="lightGem004" geometry={nodes.lightGem004.geometry} material={materials.fresnelGlow} position={[-0.756, -0.311, -0.001]} rotation={[Math.PI / 2, -1.384, Math.PI / 2]} scale={10} />
      <mesh name="object1063" geometry={nodes.object1063.geometry} material={materials['floor.003']} position={[-0.867, -0.643, -0.001]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.5} />
      <mesh name="object2008" geometry={nodes.object2008.geometry} material={materials['oldwood.004']} position={[-0.867, -0.643, -0.001]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.5} />
      <group name="upperwALL" position={[-5, -0.9, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh name="object1093" geometry={nodes.object1093.geometry} material={materials.Wall} />
        <mesh name="object1093_1" geometry={nodes.object1093_1.geometry} material={materials.sandTrim} />
      </group>
      <mesh name="stairs" geometry={nodes.stairs.geometry} material={materials.floor} position={[-2, -1.9, -1]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/LibraryStairsNew-transformed.glb')
