/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryStairsWalls.glb -t -k -i 
Files: LibraryStairsWalls.glb [16.25KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryStairsWalls-transformed.glb [2.58KB] (84%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object1005: THREE.Mesh;
    object1003: THREE.Mesh;
  };
  materials: {
    ["Sandstone_Trim.025"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LibraryStairsWalls-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="object1005"
        geometry={nodes.object1005.geometry}
        material={materials["Sandstone_Trim.025"]}
        position={[-5, -1.9, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1003"
        geometry={nodes.object1003.geometry}
        material={"transparent"}
        position={[-5, -0.9, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/LibraryStairsWalls-transformed.glb");
