/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryStairsNoColliders.glb -t -k -i -T 
Files: LibraryStairsNoColliders.glb [51.34KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryStairsNoColliders-transformed.glb [6.78KB] (87%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object1083: THREE.Mesh;
    object1083_1: THREE.Mesh;
    object1: THREE.Mesh;
    object1036: THREE.Mesh;
  };
  materials: {
    ["Sandstone_5.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.019"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LibraryStairsNoColliders-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="object1021"
        position={[-0.1, -0.9, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          name="object1083"
          geometry={nodes.object1083.geometry}
          material={materials["Sandstone_5.003"]}
        />
        <mesh
          name="object1083_1"
          geometry={nodes.object1083_1.geometry}
          material={materials["Sandstone_Trim.019"]}
        />
      </group>
      <mesh
        name="object1"
        geometry={nodes.object1.geometry}
        material={materials["Sandstone_Floor.008"]}
        position={[-2, -1.9, -1]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1036"
        geometry={nodes.object1036.geometry}
        material={materials["Sandstone_4.001"]}
        position={[-1.5, -1.9, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/LibraryStairsNoColliders-transformed.glb");
