/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cabinet.glb -t -k -i -T 
Files: cabinet.glb [134.64KB] > /home/tomoon/Documents/archiveOfBabel/public/models/cabinet-transformed.glb [19.79KB] (85%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CabinetNew: THREE.Mesh
  }
  materials: {
    oldwood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cabinet-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.oldwood} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
    </group>
  )
}

useGLTF.preload('/cabinet-transformed.glb')
