/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryStairsNewColliders.glb -t -k -i -T 
Files: LibraryStairsNewColliders.glb [16.4KB] > /home/tomoon/Documents/archiveOfBabel/public/models/LibraryStairsNewColliders-transformed.glb [4.56KB] (72%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    floor2: THREE.Mesh
    ramp: THREE.Mesh
  }
  materials: {
    floor: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryStairsNewColliders-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="floor2" geometry={nodes.floor2.geometry} material={materials.floor} position={[-1, 0.1, -1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="ramp" geometry={nodes.ramp.geometry} material={nodes.ramp.material} position={[-2, -1.9, -1]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/LibraryStairsNewColliders-transformed.glb')
