/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridorColliders.glb -t -k -i -T 
Files: LibraryCorridorColliders.glb [10KB] > /home/tomoon/Documents/archiveOfBabel/public/models/LibraryCorridorColliders-transformed.glb [1.3KB] (87%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    col: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridorColliders-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="col" geometry={nodes.col.geometry} material={nodes.col.material} position={[0, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridorColliders-transformed.glb')
