/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 libraryMainRoomColliders.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ColliderResult = GLTF & {
  nodes: {
    lowerwallCol: THREE.Mesh
    floorCol: THREE.Mesh
    railing1: THREE.Mesh
    railing3: THREE.Mesh
    railing2: THREE.Mesh
    railing4: THREE.Mesh
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/libraryMainRoomColliders.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lowerwallCol.geometry} material={nodes.lowerwallCol.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.floorCol.geometry} material={nodes.floorCol.material} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.railing1.geometry} material={nodes.railing1.material} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.75]} />
      <mesh geometry={nodes.railing3.geometry} material={nodes.railing3.material} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 0.75]} />
      <mesh geometry={nodes.railing2.geometry} material={nodes.railing2.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 0.75]} />
      <mesh geometry={nodes.railing4.geometry} material={nodes.railing4.material} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 0.75]} />
    </group>
  )
}

useGLTF.preload('/libraryMainRoomColliders.glb')
