/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridor.glb -t -k -i -T 
Files: LibraryCorridor.glb [442.32KB] > /home/tomoon/Documents/archiveOfBabel/public/models/LibraryCorridor-transformed.glb [237KB] (46%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    col: THREE.Mesh
    door: THREE.Mesh
    object1007: THREE.Mesh
    object1008: THREE.Mesh
    lightGem004: THREE.Mesh
    object1063: THREE.Mesh
    object2008: THREE.Mesh
  }
  materials: {
    floor: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    ['Sandstone_5.005']: THREE.MeshStandardMaterial
    sandstonetrim: THREE.MeshStandardMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="col" geometry={nodes.col.geometry} material={materials.floor} position={[0, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="door" geometry={nodes.door.geometry} material={materials.wall} position={[0, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1007" geometry={nodes.object1007.geometry} material={materials['Sandstone_5.005']} position={[1, 0.1, -1.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1008" geometry={nodes.object1008.geometry} material={materials.sandstonetrim} position={[1, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="lightGem004" geometry={nodes.lightGem004.geometry} material={materials['fresnelGlow.004']} position={[0, 0.664, 0.443]} rotation={[2.955, 0, Math.PI]} scale={10} />
      <mesh name="object1063" geometry={nodes.object1063.geometry} material={materials['floor.001']} position={[0, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
      <mesh name="object2008" geometry={nodes.object2008.geometry} material={materials.oldwood} position={[0, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridor-transformed.glb')
