/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 book.glb -t -k -i -T 
Files: book.glb [5.94KB] > /home/tomoon/Documents/archiveOfBabel/public/book-transformed.glb [1.51KB] (75%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Book: THREE.Mesh
  }
  materials: {
    ['Palette.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export const Book = ({position}: {position:THREE.Vector3}) => {
  const { nodes } = useGLTF('/book-transformed.glb') as GLTFResult
  return (
      <mesh position={position} name="Book" geometry={nodes.Book.geometry} rotation={[0, 0, 0]} scale={[0.75,1,1]} />
  )
}

useGLTF.preload('/book-transformed.glb')
