/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 book.glb -t -k -i -T 
Files: book.glb [6.92KB] > /home/tomoon/Documents/archiveOfBabel/public/book-transformed.glb [2.43KB] (65%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Book_1: THREE.Mesh;
    Book_2: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/book-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Book" rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
        <mesh
          name="Book_1"
          geometry={nodes.Book_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Book_2"
          geometry={nodes.Book_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/book-transformed.glb");
