/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 book.glb -t -k -i -T 
Files: book.glb [5.94KB] > /home/tomoon/Documents/archiveOfBabel/public/book-transformed.glb [1.51KB] (75%)
*/

import * as THREE from 'three';
import React, { useLayoutEffect, useRef, useState } from 'react';
import { Outlines, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { HighlightMaterial } from '../HighlightMaterial.ts/HighlightMaterial';

export type GLTFResult = GLTF & {
  nodes: {
    Book: THREE.Mesh;
  };
  materials: {
    ['Palette.001']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

const tempBook = new THREE.Object3D();
const shelfs = 10;
const rows = 4;
const cabinets = 4; // Including 3 more cabinets
const startVector = new THREE.Vector3(0.055, 0, -0.15);

export const Books = () => {
  const ref = useRef();
  const { nodes } = useGLTF('/book-transformed.glb') as GLTFResult;
  const [hoveredIndex, setHoveredIndex] = useState<number | undefined>(undefined);

  useLayoutEffect(() => {
    if (ref.current) {
      let index = 0;
      for (let k = -2; k < cabinets - 2; k++) {
        for (let j = 0; j < rows; j++) {
          for (let i = 0; i < shelfs; i++) {
            tempBook.position.copy(startVector).add(new THREE.Vector3(0.043 * i + k * 0.5, 0, -0.25 * j));
            tempBook.scale.set(0.6, 0.5, 0.45);
            tempBook.updateMatrix();
            ref.current.setMatrixAt(index++, tempBook.matrix);
          }
        }
      }
      ref.current.instanceMatrix.needsUpdate = true;
    }
  }, [nodes,hoveredIndex]);

  useLayoutEffect(() => {
    console.log(hoveredIndex);
  }, [hoveredIndex]);

  return (
    <group rotation={new THREE.Euler(0, Math.PI / 4)}>
      <instancedMesh
        onPointerEnter={(event) => setHoveredIndex(event.instanceId)}
        position={new THREE.Vector3(0, 0, -2.7)}
        rotation={new THREE.Euler(Math.PI / 2, 0, 0)}
        ref={ref}
        args={[nodes.Book.geometry, new THREE.MeshNormalMaterial, rows * shelfs * cabinets]}
      >
        <meshStandardMaterial
          attach="material"
          color={(index: number | undefined) => {
            console.log(index)
          }}
        />
      </instancedMesh>
    </group>
  );
};
