/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainNoColliders.glb -t -k -i -T 
Files: LibraryMainNoColliders.glb [182.12KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainNoColliders-transformed.glb [27.07KB] (85%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1024: THREE.Mesh
    object1024_1: THREE.Mesh
    object1055: THREE.Mesh
  }
  materials: {
    SandstoneTrim: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    ['floor.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryMainNoColliders-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="object1" rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="object1024" geometry={nodes.object1024.geometry} material={materials.SandstoneTrim} />
        <mesh name="object1024_1" geometry={nodes.object1024_1.geometry} material={materials.wall} />
      </group>
      <mesh name="object1055" geometry={nodes.object1055.geometry} material={materials['floor.004']} position={[0, 2, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/LibraryMainNoColliders-transformed.glb')
