/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainRailing.glb -t -k -i -T 
Files: LibraryMainRailing.glb [105.97KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainRailing-transformed.glb [20.99KB] (80%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1051: THREE.Mesh
  }
  materials: {
    oldwood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryMainRailing-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object1051" geometry={nodes.object1051.geometry} material={materials.oldwood} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.75]} />
    </group>
  )
}

useGLTF.preload('/LibraryMainRailing-transformed.glb')
