/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainFloorsWalls.glb -t -k -i -T 
Files: LibraryMainFloorsWalls.glb [57.84KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainFloorsWalls-transformed.glb [19.28KB] (67%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1003: THREE.Mesh
    object1008: THREE.Mesh
    object2: THREE.Mesh
  }
  materials: {
    ['floor.001']: THREE.MeshStandardMaterial
    ['wall.008']: THREE.MeshStandardMaterial
    SandstoneTrim: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryMainFloorsWalls-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object1003" geometry={nodes.object1003.geometry} material={materials['floor.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1008" geometry={nodes.object1008.geometry} material={materials['wall.008']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object2" geometry={nodes.object2.geometry} material={materials.SandstoneTrim} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/LibraryMainFloorsWalls-transformed.glb')
