/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainRailing.glb -t -k -s 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object1030: THREE.Mesh;
    object1030_1: THREE.Mesh;
    object1036: THREE.Mesh;
    object1036_1: THREE.Mesh;
    object1037: THREE.Mesh;
    object1037_1: THREE.Mesh;
    object1129: THREE.Mesh;
    object1129_1: THREE.Mesh;
  };
  materials: {
    ["Sandstone_5.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.002"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.016"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.005"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.017"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.006"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/LibraryMainRailing.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="object1001"
        position={[0.5, 0.15, -0.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 0.75]}
      >
        <mesh
          name="object1030"
          castShadow
          receiveShadow
          geometry={nodes.object1030.geometry}
          material={materials["Sandstone_5.008"]}
        />
        <mesh
          name="object1030_1"
          castShadow
          receiveShadow
          geometry={nodes.object1030_1.geometry}
          material={materials["Sandstone_4.002"]}
        />
      </group>
      <group
        name="object1015"
        position={[0.5, 0.15, 0.5]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 1, 0.75]}
      >
        <mesh
          name="object1036"
          castShadow
          receiveShadow
          geometry={nodes.object1036.geometry}
          material={materials["Sandstone_5.016"]}
        />
        <mesh
          name="object1036_1"
          castShadow
          receiveShadow
          geometry={nodes.object1036_1.geometry}
          material={materials["Sandstone_4.005"]}
        />
      </group>
      <group
        name="object1016"
        position={[-0.5, 0.15, 0.5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.75]}
      >
        <mesh
          name="object1037"
          castShadow
          receiveShadow
          geometry={nodes.object1037.geometry}
          material={materials["Sandstone_5.017"]}
        />
        <mesh
          name="object1037_1"
          castShadow
          receiveShadow
          geometry={nodes.object1037_1.geometry}
          material={materials["Sandstone_4.006"]}
        />
      </group>
      <group
        name="object1014"
        position={[-0.5, 0.15, -0.5]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.75]}
      >
        <mesh
          name="object1129"
          castShadow
          receiveShadow
          geometry={nodes.object1129.geometry}
          material={materials["Sandstone_5.003"]}
        />
        <mesh
          name="object1129_1"
          castShadow
          receiveShadow
          geometry={nodes.object1129_1.geometry}
          material={materials["Sandstone_4.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/LibraryMainRailing.glb");
