/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainNoColliders.glb -t -k -i -T 
Files: LibraryMainNoColliders.glb [306.04KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainNoColliders-transformed.glb [20.42KB] (93%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object1004: THREE.Mesh;
    object2: THREE.Mesh;
    object1006: THREE.Mesh;
    object1001: THREE.Mesh;
    object1150: THREE.Mesh;
  };
  materials: {
    ["Sandstone_Floor.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.002"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LibraryMainNoColliders-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="object1004"
        geometry={nodes.object1004.geometry}
        material={materials["Sandstone_Floor.008"]}
        position={[0.5, 0.1, -0.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="object2"
        geometry={nodes.object2.geometry}
        material={materials["Sandstone_5.001"]}
        position={[0, 0.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1006"
        geometry={nodes.object1006.geometry}
        material={materials["Sandstone_Trim.003"]}
        position={[1, 0.1, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="object1001"
        geometry={nodes.object1001.geometry}
        material={materials["Sandstone_4.002"]}
        position={[0.5, 0.15, -0.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 0.75]}
      />
      <instancedMesh
        args={[nodes.object1150.geometry, materials["Sandstone_5.001"], 8]}
        name="object1150"
        instanceMatrix={nodes.object1150.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/LibraryMainNoColliders-transformed.glb");
