/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ShelfUnit.glb -t -k -i -T 
Files: ShelfUnit.glb [73.12KB] > /home/tomoon/Documents/archiveOfBabel/public/ShelfUnit-transformed.glb [6.17KB] (92%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Drawer-Cabinet_(Alternative)"]: THREE.Mesh;
  };
  materials: {
    darkwood: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/ShelfUnit-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Drawer-Cabinet_(Alternative)"
        geometry={nodes["Drawer-Cabinet_(Alternative)"].geometry}
        material={materials.darkwood}
        position={[2.503, 0.09, -1.477]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={[0.833, 0.5, 0.5]}
      />
    </group>
  );
}

useGLTF.preload("/ShelfUnit-transformed.glb");
