/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ShelfUnit.glb -t -k -i -T 
Files: ShelfUnit.glb [15.55KB] > /home/tomoon/Documents/archiveOfBabel/public/ShelfUnit-transformed.glb [2.04KB] (87%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Book } from './Book'
import { Books } from './Books'

type GLTFResult = GLTF & {
  nodes: {
    ['Drawer-Cabinet_(Alternative)']: THREE.Mesh
  }
  materials: {
    ['Palette.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ShelfUnit-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Drawer-Cabinet_(Alternative)" geometry={nodes['Drawer-Cabinet_(Alternative)'].geometry} material={materials['Palette.004']} position={[1.47, 0.1, -2.53]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={[0.833, 0.5, 0.5]} />
    </group>
  )
}

useGLTF.preload('/ShelfUnit-transformed.glb')
