/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cabinet.glb -t -k -i -T 
Files: cabinet.glb [20KB] > /home/tomoon/Documents/archiveOfBabel/public/models/cabinet-transformed.glb [11.77KB] (41%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useCellHex } from "@/hooks/useCellHex";
import { CellHex } from "@/types/CommonTypes";
import { RigidBody } from "@react-three/rapier";
import { gameController } from "@/Controllers/gameController";
import { _objectIsEqual } from "@/lib/comparisons";
import cabinetModel from '@/assets/models/cabinet-transformed.glb'

type GLTFResult = GLTF & {
  nodes: {
    CabinetNew: THREE.Mesh
  }
  materials: {
    oldwood: THREE.MeshStandardMaterial
  }
}

type CabinetProps = {
  cellHex: CellHex;
  hasColliders?: boolean;
};

const CabinetArray: React.FC<{ position: THREE.Vector3 }> = ({ position }) => {
  const { nodes, materials } = useGLTF(cabinetModel) as GLTFResult;
  return (
    <group position={position} dispose={null}>
      <group rotation={[0, 0, 0]}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.oldwood} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.oldwood} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
      </group>
      <group rotation={[0, Math.PI, 0]}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.oldwood} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
      </group>
      <group rotation={[0, -Math.PI / 2, 0]}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.oldwood} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
      </group>
    </group>
  );
};

export const Cabinets: React.FC<CabinetProps> = ({ cellHex }) => {
  const { adjustedPosition } = useCellHex({ cellHex });
  const { cellHex: playerCellHex } = gameController();

  return _objectIsEqual(cellHex, playerCellHex) ? (
    <RigidBody type="fixed" colliders="hull">
      <CabinetArray position={adjustedPosition} />
    </RigidBody>
  ) : (
    <CabinetArray position={adjustedPosition} />
  );
};

useGLTF.preload(cabinetModel);
