/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 libraryMainRoom.glb -t -k -i -T 
Files: libraryMainRoom.glb [703.33KB] > /home/tomoon/Documents/archiveOfBabel/public/models/libraryMainRoom-transformed.glb [271.37KB] (61%)
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";
import { CellLocation } from "@/types/CommonTypes";
import { playerPos } from "../Screen/Game/components/Player/Player";
import { _objectIsEqual } from "@/lib/comparisons";
import { gameController } from "@/Controllers/gameController";
import { useCellLocation } from "../hooks/useCellLocation";
import { Text } from "@react-three/drei";
import { Cabinet } from "./Cabinets";
import { Books } from "./Books";
import { MainTorch } from "./MainTorch";

type GLTFResult = GLTF & {
  nodes: {
    lowerwallCol: THREE.Mesh;
    floorCol: THREE.Mesh;
    railing1: THREE.Mesh;
    object1004: THREE.Mesh;
    lightGem004: THREE.Mesh;
    object1063: THREE.Mesh;
    object2008: THREE.Mesh;
  };
  materials: {
    WallBake: THREE.MeshStandardMaterial;
    floor: THREE.MeshStandardMaterial;
    SandstoneTrim: THREE.MeshStandardMaterial;
    oldwood: THREE.MeshStandardMaterial;
    fresnelGlow: THREE.MeshStandardMaterial;
    ["floor.003"]: THREE.MeshStandardMaterial;
    ["oldwood.004"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const LibraryMainRoom: React.FC<{
  cellLocation: CellLocation;
  hasColliders?: boolean;
  hasLights?: boolean;
}> = ({ cellLocation, hasColliders = true, hasLights = false }) => {
  const { nodes, materials } = useGLTF(
    "/models/libraryMainRoom-transformed.glb",
  ) as GLTFResult;
  const { nodes: colliders } = useGLTF(
    "/models/libraryMainRoomColliders.glb",
  ) as GLTFResult;

  const { playerPosition, setPlayerPosition, debug } = gameController();
  const roomRef = useRef(undefined);
  const { adjustedPosition } = useCellLocation({ cellLocation });

  useEffect(() => {
    const interval = setInterval(() => {
      if (roomRef.current) {
        const bb = new THREE.Box3().setFromObject(roomRef.current);
        const inside = bb.containsPoint(playerPos);
        if (inside && !_objectIsEqual(cellLocation, playerPosition)) {
          console.log(cellLocation, playerPosition, inside);
          setPlayerPosition(cellLocation);
        }
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [roomRef, playerPosition, cellLocation]);

  return (
    <group ref={roomRef} position={adjustedPosition} dispose={null}>
      {debug && (
        <Text position={new THREE.Vector3(0, 1, 0)}>
          {`${cellLocation.x}_${cellLocation.y}_${cellLocation.z}`}
          <meshNormalMaterial />
        </Text>
      )}
      {hasColliders && (
        <>
          <RigidBody type="fixed" colliders="trimesh">
            <mesh
              geometry={colliders.lowerwallCol.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </RigidBody>
          <RigidBody type="fixed" colliders="hull">
            <mesh
              geometry={colliders.floorCol.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, Math.PI]}
            />
            <mesh
              geometry={colliders.railing1.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 1, 0.75]}
            />
            <mesh
              geometry={colliders.railing3.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 1, 0.75]}
            />
            <mesh
              geometry={colliders.railing2.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 1, 0.75]}
            />
            <mesh
              geometry={colliders.railing4.geometry}
              material={"transparent"}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={[1, 1, 0.75]}
            />
          </RigidBody>
        </>
      )}
      {hasLights && (
        <pointLight
          color={"#ebf5fe"}
          position={[0, 1.5, -2.5]}
          distance={20}
          intensity={2}
        />
      )}
      <mesh
        name="lowerwallCol"
        geometry={nodes.lowerwallCol.geometry}
        material={materials.WallBake}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="floorCol"
        geometry={nodes.floorCol.geometry}
        material={materials.floor}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="railing1"
        geometry={nodes.railing1.geometry}
        material={materials.oldwood}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.75]}
      />
      <mesh
        name="object1004"
        geometry={nodes.object1004.geometry}
        material={materials["SandstoneTrim.008"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="lightGem004"
        geometry={nodes.lightGem004.geometry}
        material={materials.fresnelGlow}
        position={[0, 1.589, -2.845]}
        rotation={[0.187, 0, 0]}
        scale={10}
      />
      <mesh
        name="object1063"
        geometry={nodes.object1063.geometry}
        material={materials["floor.003"]}
        position={[0, 1.257, -2.734]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <mesh
        name="object2008"
        geometry={nodes.object2008.geometry}
        material={materials["oldwood.004"]}
        position={[0, 1.257, -2.734]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  );
};

useGLTF.preload("/libraryMainRoom-transformed.glb");
