/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridor.glb -t -k -i -T 
Files: LibraryCorridor.glb [422.94KB] > /home/tomoon/Documents/archiveOfBabel/public/models/LibraryCorridor-transformed.glb [236.16KB] (44%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Orientation, CellHex } from "@/types/CommonTypes";
import { RigidBody } from "@react-three/rapier";
import { useCellHex } from "../hooks/useCellHex";
import { transparentMaterial } from "@/lib/materials";
import { adjustments } from "@/lib/positions";
import LibraryCorridorModel from '@/assets/models/Corridor-transformed.glb'
import LibraryCorridorColliders from '@/assets/models/LibraryCorridorColliders-transformed.glb'

type GLTFResult = GLTF & {
  nodes: {
    col004: THREE.Mesh
    door012: THREE.Mesh
    object1083: THREE.Mesh
    lightGem007: THREE.Mesh
    object1092: THREE.Mesh
    object2026: THREE.Mesh
  }
  materials: {
    floorNormalizedCoridor: THREE.MeshBasicMaterial
    wallCorridorNormailzed: THREE.MeshBasicMaterial
    detailCorridor: THREE.MeshBasicMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
  }
}

export const LibraryCorridor: React.FC<{
  cellHex: CellHex;
  orientation: Orientation;
  hasColliders?: boolean;
  demo?: boolean;
}> = ({
  cellHex,
  orientation,
  hasColliders = true,
  demo = false,
}) => {
  const { adjustedPosition } = useCellHex({
    cellHex,
    addition: adjustments[orientation]
  });

  const { nodes, materials } = useGLTF(LibraryCorridorModel) as GLTFResult;
  const { nodes: colliders } = useGLTF(LibraryCorridorColliders) as GLTFResult;

  return (
    <group
      rotation={new THREE.Euler(0, ["N", "S"].includes(orientation) ? Math.PI / 2 : 0, 0)}
      position={adjustedPosition}
      dispose={null}
    >
      {hasColliders && (
        <RigidBody colliders={"trimesh"} type="fixed">
          <mesh
            name="col"
            geometry={colliders.col.geometry}
            material={transparentMaterial}
            position={[0, 0.1, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </RigidBody>
      )}
      {
        demo && (
          <pointLight
            color={"#ebf5fe"}
            position={[0, 0.5, 0]}
            distance={20}
            intensity={2}
          />
        )
      }
      <mesh name="col" geometry={nodes.col004.geometry} material={materials.floorNormalizedCoridor} position={[0, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="door" geometry={nodes.door012.geometry} material={materials.wallCorridorNormailzed} position={[0, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1005" geometry={nodes.object1083.geometry} material={materials.detailCorridor} position={[0, 0.1, 0.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="lightGem004" geometry={nodes.lightGem007.geometry} material={materials['fresnelGlow.004']} position={[0, 0.664, 0.443]} rotation={[2.955, 0, Math.PI]} scale={10} />
      <mesh name="object1063" geometry={nodes.object1092.geometry} material={materials['floor.001']} position={[0, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
      <mesh name="object2008" geometry={nodes.object2026.geometry} material={materials.oldwood} position={[0, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
     </group>
  );
};

useGLTF.preload(LibraryCorridorModel);
useGLTF.preload(LibraryCorridorColliders);