/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainFloorsWalls.glb -t -k -s 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object2: THREE.Mesh;
    object1006: THREE.Mesh;
    object1005: THREE.Mesh;
    object1007: THREE.Mesh;
    object2001: THREE.Mesh;
    object1028: THREE.Mesh;
    object1029: THREE.Mesh;
    object1030: THREE.Mesh;
    object2002: THREE.Mesh;
    object1031: THREE.Mesh;
    object1032: THREE.Mesh;
    object1033: THREE.Mesh;
    object2003: THREE.Mesh;
    object1034: THREE.Mesh;
    object1035: THREE.Mesh;
    object1036: THREE.Mesh;
    object1004: THREE.Mesh;
    object1023: THREE.Mesh;
    object1024: THREE.Mesh;
    object1025: THREE.Mesh;
  };
  materials: {
    ["Sandstone_5.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.002"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.004"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.027"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.014"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.015"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.026"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.029"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.016"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.017"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.028"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.030"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.018"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.019"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.031"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.010"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.011"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.012"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LibraryMainFloorsWalls.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="object2"
        castShadow
        receiveShadow
        geometry={nodes.object2.geometry}
        material={materials["Sandstone_5.001"]}
        position={[0, 0.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1006"
        castShadow
        receiveShadow
        geometry={nodes.object1006.geometry}
        material={materials["Sandstone_Trim.003"]}
        position={[1, 0.1, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="object1005"
        castShadow
        receiveShadow
        geometry={nodes.object1005.geometry}
        material={materials["Sandstone_5.002"]}
        position={[1, 0.1, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="object1007"
        castShadow
        receiveShadow
        geometry={nodes.object1007.geometry}
        material={materials["Sandstone_Trim.004"]}
        position={[0, 0.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object2001"
        castShadow
        receiveShadow
        geometry={nodes.object2001.geometry}
        material={materials["Sandstone_5.027"]}
        position={[-3.5, 0.1, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1028"
        castShadow
        receiveShadow
        geometry={nodes.object1028.geometry}
        material={materials["Sandstone_Trim.014"]}
        position={[-3.5, 0.1, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1029"
        castShadow
        receiveShadow
        geometry={nodes.object1029.geometry}
        material={materials["Sandstone_Trim.015"]}
        position={[-1.5, 0.1, -1]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1030"
        castShadow
        receiveShadow
        geometry={nodes.object1030.geometry}
        material={materials["Sandstone_5.026"]}
        position={[-1.5, 0.1, -1]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object2002"
        castShadow
        receiveShadow
        geometry={nodes.object2002.geometry}
        material={materials["Sandstone_5.029"]}
        position={[0, 0.1, 3.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="object1031"
        castShadow
        receiveShadow
        geometry={nodes.object1031.geometry}
        material={materials["Sandstone_Trim.016"]}
        position={[0, 0.1, 3.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="object1032"
        castShadow
        receiveShadow
        geometry={nodes.object1032.geometry}
        material={materials["Sandstone_Trim.017"]}
        position={[-1, 0.1, 1.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1033"
        castShadow
        receiveShadow
        geometry={nodes.object1033.geometry}
        material={materials["Sandstone_5.028"]}
        position={[-1, 0.1, 1.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object2003"
        castShadow
        receiveShadow
        geometry={nodes.object2003.geometry}
        material={materials["Sandstone_5.030"]}
        position={[3.5, 0.1, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1034"
        castShadow
        receiveShadow
        geometry={nodes.object1034.geometry}
        material={materials["Sandstone_Trim.018"]}
        position={[3.5, 0.1, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1035"
        castShadow
        receiveShadow
        geometry={nodes.object1035.geometry}
        material={materials["Sandstone_Trim.019"]}
        position={[1.5, 0.1, 1]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1036"
        castShadow
        receiveShadow
        geometry={nodes.object1036.geometry}
        material={materials["Sandstone_5.031"]}
        position={[1.5, 0.1, 1]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1004"
        castShadow
        receiveShadow
        geometry={nodes.object1004.geometry}
        material={materials["Sandstone_Floor.008"]}
        position={[0.5, 0.1, -0.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="object1023"
        castShadow
        receiveShadow
        geometry={nodes.object1023.geometry}
        material={materials["Sandstone_Floor.010"]}
        position={[0.5, 0.1, 0.5]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1024"
        castShadow
        receiveShadow
        geometry={nodes.object1024.geometry}
        material={materials["Sandstone_Floor.011"]}
        position={[-0.5, 0.1, -0.5]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1025"
        castShadow
        receiveShadow
        geometry={nodes.object1025.geometry}
        material={materials["Sandstone_Floor.012"]}
        position={[-0.5, 0.1, 0.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/LibraryMainFloorsWalls.glb");
