/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainNoColliders.glb -t -k -i 
Files: LibraryMainNoColliders.glb [162.22KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainNoColliders-transformed.glb [11.81KB] (93%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object1022: THREE.Mesh;
    object1008: THREE.Mesh;
    object1009: THREE.Mesh;
    object1026: THREE.Mesh;
    object1026_1: THREE.Mesh;
    object1027: THREE.Mesh;
    object1150: THREE.Mesh;
  };
  materials: {
    ["Sandstone_5.023"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.005"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LibraryMainNoColliders-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="object1022"
        geometry={nodes.object1022.geometry}
        material={materials["Sandstone_5.023"]}
        position={[0.5, 0.1, 0.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="object1008"
        geometry={nodes.object1008.geometry}
        material={materials["Sandstone_Trim.005"]}
        position={[1, 1.1, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="object1009"
        geometry={nodes.object1009.geometry}
        material={nodes.object1009.material}
        position={[0, 1.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <instancedMesh
        args={[nodes.object1027.geometry, materials["Sandstone_5.023"], 8]}
        name="object1027"
        instanceMatrix={nodes.object1027.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1150.geometry, materials["Sandstone_5.023"], 8]}
        name="object1150"
        instanceMatrix={nodes.object1150.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1026.geometry, materials["Sandstone_Trim.005"], 8]}
        name="object1026"
        instanceMatrix={nodes.object1026.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1026_1.geometry, materials["Sandstone_5.023"], 8]}
        name="object1026_1"
        instanceMatrix={nodes.object1026_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/LibraryMainNoColliders-transformed.glb");
