/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 book.glb -t -k -i -T 
Files: book.glb [15.31KB] > /home/tomoon/Documents/archiveOfBabel/public/book-transformed.glb [2.66KB] (83%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Book: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/book-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Book" geometry={nodes.Book.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/book-transformed.glb')
