/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Cabinets.glb -t -k -i -T 
Files: Cabinets.glb [1.04MB] > /home/tomoon/Documents/archiveOfBabel/public/Cabinets-transformed.glb [51.2KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CabinetNew: THREE.Mesh
  }
  materials: {
    cabinet: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Cabinets-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="CabinetNew" geometry={nodes.CabinetNew.geometry} material={materials.cabinet} position={[1.95, 0.702, 1.95]} rotation={[0, Math.PI / 4, 0]} />
    </group>
  )
}

useGLTF.preload('/Cabinets-transformed.glb')
