/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Corridor.glb -t -k -i -T 
Files: Corridor.glb [2.25MB] > /home/tomoon/Documents/archiveOfBabel/public/Corridor-transformed.glb [133.26KB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    col: THREE.Mesh
    door: THREE.Mesh
    object1005: THREE.Mesh
    lightGem004: THREE.Mesh
    object1063: THREE.Mesh
    object2008: THREE.Mesh
  }
  materials: {
    floorNormalizedCoridor: THREE.MeshBasicMaterial
    wallCorridorNormailzed: THREE.MeshBasicMaterial
    detailCorridor: THREE.MeshBasicMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Corridor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="col" geometry={nodes.col.geometry} material={materials.floorNormalizedCoridor} position={[-5.5, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="door" geometry={nodes.door.geometry} material={materials.wallCorridorNormailzed} position={[-5.5, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1005" geometry={nodes.object1005.geometry} material={materials.detailCorridor} position={[-5.5, 0.1, 0.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="lightGem004" geometry={nodes.lightGem004.geometry} material={materials['fresnelGlow.004']} position={[-5.5, 0.664, 0.443]} rotation={[2.955, 0, Math.PI]} scale={10} />
      <mesh name="object1063" geometry={nodes.object1063.geometry} material={materials['floor.001']} position={[-5.5, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
      <mesh name="object2008" geometry={nodes.object2008.geometry} material={materials.oldwood} position={[-5.5, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/Corridor-transformed.glb')
