/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Corridor.glb -t -k -i -T 
Files: Corridor.glb [2.45MB] > /home/tomoon/Documents/archiveOfBabel/public/Corridor-transformed.glb [190.06KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    col004: THREE.Mesh
    door012: THREE.Mesh
    object1083: THREE.Mesh
    lightGem007: THREE.Mesh
    object1092: THREE.Mesh
    object2026: THREE.Mesh
  }
  materials: {
    floorNormalizedCoridor: THREE.MeshBasicMaterial
    wallCorridorNormailzed: THREE.MeshBasicMaterial
    detailCorridor: THREE.MeshBasicMaterial
    ['fresnelGlow.004']: THREE.MeshPhysicalMaterial
    ['floor.001']: THREE.MeshPhysicalMaterial
    oldwood: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Corridor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="col004" geometry={nodes.col004.geometry} material={materials.floorNormalizedCoridor} position={[-5.5, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="door012" geometry={nodes.door012.geometry} material={materials.wallCorridorNormailzed} position={[-5.5, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1083" geometry={nodes.object1083.geometry} material={materials.detailCorridor} position={[-5.5, 0.1, 0.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="lightGem007" geometry={nodes.lightGem007.geometry} material={materials['fresnelGlow.004']} position={[-5.5, 0.664, 0.443]} rotation={[2.955, 0, Math.PI]} scale={10} />
      <mesh name="object1092" geometry={nodes.object1092.geometry} material={materials['floor.001']} position={[-5.5, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
      <mesh name="object2026" geometry={nodes.object2026.geometry} material={materials.oldwood} position={[-5.5, 0.333, 0.332]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/Corridor-transformed.glb')
