/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 LibraryStairs.glb -t -k -i -T 
Files: LibraryStairs.glb [517.62KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryStairs-transformed.glb [240.56KB] (54%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    stairs: THREE.Mesh
    object1093: THREE.Mesh
    object1093_1: THREE.Mesh
    lightGem001: THREE.Mesh
    object1002: THREE.Mesh
    object2004: THREE.Mesh
  }
  materials: {
    floornormalized: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    sandstomenormalized: THREE.MeshStandardMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryStairs-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="stairs" geometry={nodes.stairs.geometry} material={materials.floornormalized} position={[-4.497, 0.1, -2.005]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <group name="upperwALL" position={[-5.497, 1.1, -5.005]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="object1093" geometry={nodes.object1093.geometry} material={materials.wall} />
        <mesh name="object1093_1" geometry={nodes.object1093_1.geometry} material={materials.sandstomenormalized} />
      </group>
      <mesh name="lightGem001" geometry={nodes.lightGem001.geometry} material={materials['fresnelGlow.004']} position={[-5.495, 1.71, -0.757]} rotation={[2.955, 0, -Math.PI]} scale={10} />
      <mesh name="object1002" geometry={nodes.object1002.geometry} material={materials['floor.001']} position={[-5.495, 1.379, -0.868]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.5} />
      <mesh name="object2004" geometry={nodes.object2004.geometry} material={materials.oldwood} position={[-5.495, 1.379, -0.868]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/LibraryStairs-transformed.glb')
