/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 MainRoom.glb -t -k -i -T 
Files: MainRoom.glb [4.73MB] > /home/tomoon/Documents/archiveOfBabel/public/MainRoom-transformed.glb [378.14KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    floorCol: THREE.Mesh
    lowerwallCol: THREE.Mesh
    object1021: THREE.Mesh
    railing1: THREE.Mesh
    lightGem008: THREE.Mesh
    object1022: THREE.Mesh
    object2011: THREE.Mesh
  }
  materials: {
    floorMainRoom: THREE.MeshBasicMaterial
    wallMainRoom: THREE.MeshBasicMaterial
    detailMainRoom: THREE.MeshBasicMaterial
    railingNormalized: THREE.MeshBasicMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MainRoom-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="floorCol" geometry={nodes.floorCol.geometry} material={materials.floorMainRoom} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="lowerwallCol" geometry={nodes.lowerwallCol.geometry} material={materials.wallMainRoom} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1021" geometry={nodes.object1021.geometry} material={materials.detailMainRoom} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="railing1" geometry={nodes.railing1.geometry} material={materials.railingNormalized} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.75]} />
      <mesh name="lightGem008" geometry={nodes.lightGem008.geometry} material={materials['fresnelGlow.004']} position={[0, 1.604, 2.853]} rotation={[2.955, 0, Math.PI]} scale={10} />
      <mesh name="object1022" geometry={nodes.object1022.geometry} material={materials['floor.001']} position={[0, 1.273, 2.742]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
      <mesh name="object2011" geometry={nodes.object2011.geometry} material={materials.oldwood} position={[0, 1.273, 2.742]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/MainRoom-transformed.glb')
