/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Stairs.glb -t -k -i -T 
Files: Stairs.glb [5.16MB] > /home/tomoon/Documents/archiveOfBabel/public/Stairs-transformed.glb [318.76KB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    stairs: THREE.Mesh
    floor2: THREE.Mesh
    lightGem001: THREE.Mesh
    object1002: THREE.Mesh
    object2004: THREE.Mesh
    DETAILS: THREE.Mesh
    upperwALL: THREE.Mesh
    upperwALL003: THREE.Mesh
  }
  materials: {
    stairsStairs: THREE.MeshBasicMaterial
    stairsFloor: THREE.MeshBasicMaterial
    ['fresnelGlow.004']: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    oldwood: THREE.MeshStandardMaterial
    stairsDetail: THREE.MeshBasicMaterial
    wallStairsOuter: THREE.MeshBasicMaterial
    wallStairsInner: THREE.MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Stairs-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="stairs" geometry={nodes.stairs.geometry} material={materials.stairsStairs} position={[-4.497, 0.1, -2.005]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh name="floor2" geometry={nodes.floor2.geometry} material={materials.stairsFloor} position={[-5.454, 1.747, -1.845]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="lightGem001" geometry={nodes.lightGem001.geometry} material={materials['fresnelGlow.004']} position={[-5.5, 1.71, -0.75]} rotation={[2.955, 0, -Math.PI]} scale={10} />
      <mesh name="object1002" geometry={nodes.object1002.geometry} material={materials['floor.001']} position={[-5.5, 1.379, -0.868]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.5} />
      <mesh name="object2004" geometry={nodes.object2004.geometry} material={materials.oldwood} position={[-5.5, 1.379, -0.868]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.5} />
      <mesh name="DETAILS" geometry={nodes.DETAILS.geometry} material={materials.stairsDetail} position={[-5.497, 1.1, -5.005]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="upperwALL" geometry={nodes.upperwALL.geometry} material={materials.wallStairsOuter} position={[-5.497, 1.1, -5.005]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="upperwALL003" geometry={nodes.upperwALL003.geometry} material={materials.wallStairsInner} position={[-5.497, 1.1, -5.005]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Stairs-transformed.glb')
