/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cabinet.glb -t -k -i -T 
Files: cabinet.glb [20KB] > /home/tomoon/Documents/archiveOfBabel/public/models/cabinet-transformed.glb [11.77KB] (41%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useCellLocation } from "@/hooks/useCellLocation";
import { CellLocation } from "@/types/CommonTypes";
import { RigidBody } from "@react-three/rapier";
import { gameController } from "@/Controllers/gameController";
import { _objectIsEqual } from "@/lib/comparisons";

type GLTFResult = GLTF & {
  nodes: {
    cabinet: THREE.Mesh;
  };
  materials: {
    oldwood: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

type CabinetProps = {
  cellLocation: CellLocation;
  hasColliders?: boolean;
};

const CabinetArray: React.FC<{ position: THREE.Vector3 }> = ({ position }) => {
  const { nodes, materials } = useGLTF(
    "/models/cabinet-transformed.glb",
  ) as GLTFResult;
  return (
    <group position={position} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <mesh
          name="cabinet"
          geometry={nodes.cabinet.geometry}
          material={materials.oldwood}
          position={[2.524, 0.09, -1.456]}
          rotation={[Math.PI / 2, 0, Math.PI / 4]}
          scale={[0.833, 0.5, 0.5]}
        />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          name="cabinet"
          geometry={nodes.cabinet.geometry}
          material={materials.oldwood}
          position={[2.524, 0.09, -1.456]}
          rotation={[Math.PI / 2, 0, Math.PI / 4]}
          scale={[0.833, 0.5, 0.5]}
        />
      </group>
      <group rotation={[0, Math.PI, 0]}>
        <mesh
          name="cabinet"
          geometry={nodes.cabinet.geometry}
          material={materials.oldwood}
          position={[2.524, 0.09, -1.456]}
          rotation={[Math.PI / 2, 0, Math.PI / 4]}
          scale={[0.833, 0.5, 0.5]}
        />
      </group>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          name="cabinet"
          geometry={nodes.cabinet.geometry}
          material={materials.oldwood}
          position={[2.524, 0.09, -1.456]}
          rotation={[Math.PI / 2, 0, Math.PI / 4]}
          scale={[0.833, 0.5, 0.5]}
        />
      </group>
    </group>
  );
};

export const Cabinets: React.FC<CabinetProps> = ({ cellLocation }) => {
  const { adjustedPosition } = useCellLocation({ cellLocation });
  const { playerPosition } = gameController();

  return _objectIsEqual(cellLocation, playerPosition) ? (
    <RigidBody type="fixed" colliders="hull">
      <CabinetArray position={adjustedPosition} />
    </RigidBody>
  ) : (
    <CabinetArray position={adjustedPosition} />
  );
};

useGLTF.preload("/cabinet-transformed.glb");
