/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cabinet.glb -t -k -i -T 
Files: cabinet.glb [20KB] > /home/tomoon/Documents/archiveOfBabel/public/models/cabinet-transformed.glb [11.77KB] (41%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    cabinet: THREE.Mesh;
  };
  materials: {
    oldwood: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Cabinet(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/cabinet-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="cabinet"
        geometry={nodes.cabinet.geometry}
        material={materials.oldwood}
        position={[2.524, 0.09, -1.456]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={[0.833, 0.5, 0.5]}
      />
    </group>
  );
}

useGLTF.preload("/cabinet-transformed.glb");
