/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 mainTorch.glb -t -k -i -T 
Files: mainTorch.glb [29.88KB] > /home/tomoon/Documents/archiveOfBabel/public/mainTorch-transformed.glb [15.22KB] (49%)
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useHelper } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { gameController } from "@/Controllers/gameController";

type GLTFResult = GLTF & {
  nodes: {
    object1063: THREE.Mesh;
    object2008: THREE.Mesh;
    lightGem004: THREE.Mesh;
  };
  materials: {
    floor: THREE.MeshStandardMaterial;
    oldwood: THREE.MeshStandardMaterial;
    ["fresnelGlow.004"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const MainTorch: React.FC<{
  props: JSX.IntrinsicElements["group"];
  active: boolean;
}> = ({ active, ...props }) => {
  const { nodes, materials } = useGLTF(
    "/mainTorch-transformed.glb",
  ) as GLTFResult;
  const { debug } = gameController();

  const lightRef = useRef(undefined);
  debug && useHelper(lightRef, THREE.PointLightHelper, 1, "cyan");

  useFrame(() => {
    if (lightRef.current) {
      lightRef.current.intensity = THREE.MathUtils.lerp(
        lightRef.current.intensity,
        active ? 2 : 0,
        0.1,
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      <pointLight
        color={"#ebf5fe"}
        position={[0, 0.332, -0.111]}
        ref={lightRef}
        distance={10}
        intensity={0}
      />
      <mesh
        name="object1063"
        geometry={nodes.object1063.geometry}
        material={materials.floor}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <mesh
        name="object2008"
        geometry={nodes.object2008.geometry}
        material={materials.oldwood}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <mesh
        name="lightGem004"
        geometry={nodes.lightGem004.geometry}
        position={[0, 0.332, -0.111]}
        rotation={[0.187, 0, 0]}
        scale={10}
      />
    </group>
  );
};

useGLTF.preload("/mainTorch-transformed.glb");
