/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryStairs.glb -t -k -s 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    steps: THREE.Mesh;
    steps3: THREE.Mesh;
    ciel001: THREE.Mesh;
    ciel002: THREE.Mesh;
    ciel004: THREE.Mesh;
    ciel007: THREE.Mesh;
    object1028: THREE.Mesh;
    steps003: THREE.Mesh;
    steps004: THREE.Mesh;
    object1: THREE.Mesh;
    object2: THREE.Mesh;
    object1001: THREE.Mesh;
    object2001: THREE.Mesh;
    object2002: THREE.Mesh;
    object1002: THREE.Mesh;
    object2003: THREE.Mesh;
    object1003: THREE.Mesh;
    object2013: THREE.Mesh;
    object2014: THREE.Mesh;
    object1013: THREE.Mesh;
    object1015: THREE.Mesh;
    object1017: THREE.Mesh;
    object1018: THREE.Mesh;
    object1025: THREE.Mesh;
    object1026: THREE.Mesh;
    object1005: THREE.Mesh;
    object1006: THREE.Mesh;
    object1009: THREE.Mesh;
    object1010: THREE.Mesh;
    object1020: THREE.Mesh;
    object1022: THREE.Mesh;
    object2004: THREE.Mesh;
    object2007: THREE.Mesh;
  };
  materials: {
    Dark_Grey: THREE.MeshStandardMaterial;
    ["Dark_Grey.003"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.009"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.012"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.042"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.048"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.046"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.043"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.045"]: THREE.MeshStandardMaterial;
    ["Grey.001"]: THREE.MeshStandardMaterial;
    ["Grey.002"]: THREE.MeshStandardMaterial;
    ["Grey.003"]: THREE.MeshStandardMaterial;
    ["Grey.004"]: THREE.MeshStandardMaterial;
    ["Grey.005"]: THREE.MeshStandardMaterial;
    ["Grey.006"]: THREE.MeshStandardMaterial;
    ["Grey.007"]: THREE.MeshStandardMaterial;
    ["Grey.026"]: THREE.MeshStandardMaterial;
    ["Grey.027"]: THREE.MeshStandardMaterial;
    ["Grey.029"]: THREE.MeshStandardMaterial;
    ["Grey.031"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.016"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.018"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.025"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.026"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.034"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.035"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.038"]: THREE.MeshStandardMaterial;
    ["Dark_Grey.039"]: THREE.MeshStandardMaterial;
    ["Grey.041"]: THREE.MeshStandardMaterial;
    ["Grey.043"]: THREE.MeshStandardMaterial;
    ["Grey.045"]: THREE.MeshStandardMaterial;
    ["Grey.048"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const LibraryStairs = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/LibraryStairs.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="steps"
        castShadow
        receiveShadow
        geometry={nodes.steps.geometry}
        material={materials.Dark_Grey}
        position={[-1.476, 0.394, -1.221]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="steps3"
        castShadow
        receiveShadow
        geometry={nodes.steps3.geometry}
        material={materials["Dark_Grey.003"]}
        position={[-2.871, 0.894, -1.174]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="ciel001"
        castShadow
        receiveShadow
        geometry={nodes.ciel001.geometry}
        material={materials["Dark_Grey.009"]}
        position={[-7.012, 2.334, -7.859]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="ciel002"
        castShadow
        receiveShadow
        geometry={nodes.ciel002.geometry}
        material={materials["Dark_Grey.012"]}
        position={[-9.509, 2.834, 4.362]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="ciel004"
        castShadow
        receiveShadow
        geometry={nodes.ciel004.geometry}
        material={materials["Dark_Grey.042"]}
        position={[5.209, 1.834, -4.363]}
        rotation={[Math.PI / 2, 0, 1.571]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="ciel007"
        castShadow
        receiveShadow
        geometry={nodes.ciel007.geometry}
        material={materials["Dark_Grey.048"]}
        position={[2.712, 1.334, 7.859]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="object1028"
        castShadow
        receiveShadow
        geometry={nodes.object1028.geometry}
        material={materials["Dark_Grey.046"]}
        position={[-3.15, -0.892, -0.148]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="steps003"
        castShadow
        receiveShadow
        geometry={nodes.steps003.geometry}
        material={materials["Dark_Grey.043"]}
        position={[-1.429, -0.106, 1.174]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="steps004"
        castShadow
        receiveShadow
        geometry={nodes.steps004.geometry}
        material={materials["Dark_Grey.045"]}
        position={[-2.825, -0.606, 1.221]}
        rotation={[Math.PI / 2, 0, -3.142]}
        scale={[1, 1, 0.5]}
      />
      <mesh
        name="object1"
        castShadow
        receiveShadow
        geometry={nodes.object1.geometry}
        material={materials["Grey.001"]}
        position={[-1.256, 0.6, -1.394]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object2"
        castShadow
        receiveShadow
        geometry={nodes.object2.geometry}
        material={materials["Grey.001"]}
        position={[-2.489, 0.6, -0.839]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1001"
        castShadow
        receiveShadow
        geometry={nodes.object1001.geometry}
        material={materials["Grey.002"]}
        position={[-3.044, 0.6, -1.394]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object2001"
        castShadow
        receiveShadow
        geometry={nodes.object2001.geometry}
        material={materials["Grey.003"]}
        position={[-1.811, 0.6, -0.839]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object2002"
        castShadow
        receiveShadow
        geometry={nodes.object2002.geometry}
        material={materials["Grey.004"]}
        position={[-1.811, 1.6, -0.839]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1002"
        castShadow
        receiveShadow
        geometry={nodes.object1002.geometry}
        material={materials["Grey.005"]}
        position={[-1.256, 1.6, -1.394]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object2003"
        castShadow
        receiveShadow
        geometry={nodes.object2003.geometry}
        material={materials["Grey.006"]}
        position={[-2.489, 1.6, -0.839]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1003"
        castShadow
        receiveShadow
        geometry={nodes.object1003.geometry}
        material={materials["Grey.007"]}
        position={[-3.044, 1.6, -1.394]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object2013"
        castShadow
        receiveShadow
        geometry={nodes.object2013.geometry}
        material={materials["Grey.026"]}
        position={[-1.811, 0.6, 0.839]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object2014"
        castShadow
        receiveShadow
        geometry={nodes.object2014.geometry}
        material={materials["Grey.027"]}
        position={[-2.49, 0.601, 0.839]}
        rotation={[Math.PI / 2, 0, -3.142]}
      />
      <mesh
        name="object1013"
        castShadow
        receiveShadow
        geometry={nodes.object1013.geometry}
        material={materials["Grey.029"]}
        position={[-1.256, 0.6, 1.394]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1015"
        castShadow
        receiveShadow
        geometry={nodes.object1015.geometry}
        material={materials["Grey.031"]}
        position={[-3.045, 0.601, 1.394]}
        rotation={[Math.PI / 2, 0, -3.142]}
      />
      <mesh
        name="object1017"
        castShadow
        receiveShadow
        geometry={nodes.object1017.geometry}
        material={materials["Dark_Grey.016"]}
        position={[-1.05, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1018"
        castShadow
        receiveShadow
        geometry={nodes.object1018.geometry}
        material={materials["Dark_Grey.018"]}
        position={[-1.6, 0.6, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1025"
        castShadow
        receiveShadow
        geometry={nodes.object1025.geometry}
        material={materials["Dark_Grey.025"]}
        position={[-2.7, 0.6, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1026"
        castShadow
        receiveShadow
        geometry={nodes.object1026.geometry}
        material={materials["Dark_Grey.026"]}
        position={[-3.6, 0.6, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1005"
        castShadow
        receiveShadow
        geometry={nodes.object1005.geometry}
        material={materials["Dark_Grey.034"]}
        position={[-0.7, -0.45, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1006"
        castShadow
        receiveShadow
        geometry={nodes.object1006.geometry}
        material={materials["Dark_Grey.035"]}
        position={[-3.6, -0.4, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1009"
        castShadow
        receiveShadow
        geometry={nodes.object1009.geometry}
        material={materials["Dark_Grey.038"]}
        position={[-2.7, -0.4, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="object1010"
        castShadow
        receiveShadow
        geometry={nodes.object1010.geometry}
        material={materials["Dark_Grey.039"]}
        position={[-1.6, -0.4, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object1020"
        castShadow
        receiveShadow
        geometry={nodes.object1020.geometry}
        material={materials["Grey.041"]}
        position={[-3.045, -0.399, 1.394]}
        rotation={[Math.PI / 2, 0, -3.142]}
      />
      <mesh
        name="object1022"
        castShadow
        receiveShadow
        geometry={nodes.object1022.geometry}
        material={materials["Grey.043"]}
        position={[-1.256, -0.399, 1.394]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="object2004"
        castShadow
        receiveShadow
        geometry={nodes.object2004.geometry}
        material={materials["Grey.045"]}
        position={[-2.49, -0.399, 0.839]}
        rotation={[Math.PI / 2, 0, -3.142]}
      />
      <mesh
        name="object2007"
        castShadow
        receiveShadow
        geometry={nodes.object2007.geometry}
        material={materials["Grey.048"]}
        position={[-1.811, -0.399, 0.839]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
};

useGLTF.preload("/LibraryStairs.glb");
