/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridor.glb -t -k -s 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    object1002: THREE.Mesh;
    object1004: THREE.Mesh;
    object1005: THREE.Mesh;
    object1013: THREE.Mesh;
    object1014: THREE.Mesh;
    object1015: THREE.Mesh;
    object1016: THREE.Mesh;
    object1017: THREE.Mesh;
    object1018: THREE.Mesh;
    object1003: THREE.Mesh;
    object2001: THREE.Mesh;
    object2002: THREE.Mesh;
    object1: THREE.Mesh;
    object1001: THREE.Mesh;
    object1006: THREE.Mesh;
    object1007: THREE.Mesh;
    object1008: THREE.Mesh;
    object1009: THREE.Mesh;
    object1010: THREE.Mesh;
    object1011: THREE.Mesh;
    object1012: THREE.Mesh;
    object1019: THREE.Mesh;
    object1020: THREE.Mesh;
    object1021: THREE.Mesh;
    object1023: THREE.Mesh;
    object1026: THREE.Mesh;
    object1022: THREE.Mesh;
    object1024: THREE.Mesh;
    object1025: THREE.Mesh;
    object1027: THREE.Mesh;
    object1028: THREE.Mesh;
    object1029: THREE.Mesh;
  };
  materials: {
    Sandstone_Floor: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.004"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.005"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.006"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.007"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.009"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.010"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.002"]: THREE.MeshStandardMaterial;
    Sandstone_Trim: THREE.MeshStandardMaterial;
    Sandstone_5: THREE.MeshStandardMaterial;
    ["Sandstone_5.004"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.005"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.006"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.007"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.009"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.010"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.011"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.012"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.014"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.017"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.018"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.019"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.020"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.021"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.022"]: THREE.MeshStandardMaterial;
    ["Sandstone_5.023"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const LibraryCorridor = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/LibraryCorridor.glb") as GLTFResult;
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          name="object1002"
          castShadow
          receiveShadow
          geometry={nodes.object1002.geometry}
          material={materials.Sandstone_Floor}
          position={[0, 0.1, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1004"
          castShadow
          receiveShadow
          geometry={nodes.object1004.geometry}
          material={materials["Sandstone_Trim.001"]}
          position={[-1, 0.1, 1.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1005"
          castShadow
          receiveShadow
          geometry={nodes.object1005.geometry}
          material={materials["Sandstone_Trim.004"]}
          position={[-2, 0.1, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1013"
          castShadow
          receiveShadow
          geometry={nodes.object1013.geometry}
          material={materials["Sandstone_Trim.005"]}
          position={[-1, 0.1, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1014"
          castShadow
          receiveShadow
          geometry={nodes.object1014.geometry}
          material={materials["Sandstone_Trim.006"]}
          position={[-2, 0.1, -1.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1015"
          castShadow
          receiveShadow
          geometry={nodes.object1015.geometry}
          material={materials["Sandstone_Trim.007"]}
          position={[1, 0.1, -1.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1016"
          castShadow
          receiveShadow
          geometry={nodes.object1016.geometry}
          material={materials["Sandstone_Trim.008"]}
          position={[2, 0.1, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1017"
          castShadow
          receiveShadow
          geometry={nodes.object1017.geometry}
          material={materials["Sandstone_Trim.009"]}
          position={[1, 0.1, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1018"
          castShadow
          receiveShadow
          geometry={nodes.object1018.geometry}
          material={materials["Sandstone_Trim.010"]}
          position={[2, 0.1, 1.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1003"
          castShadow
          receiveShadow
          geometry={nodes.object1003.geometry}
          material={materials["Sandstone_Trim.003"]}
          position={[0, 0.1, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object2001"
          castShadow
          receiveShadow
          geometry={nodes.object2001.geometry}
          material={materials["Sandstone_5.001"]}
          position={[0, 0.1, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object2002"
          castShadow
          receiveShadow
          geometry={nodes.object2002.geometry}
          material={materials["Sandstone_5.002"]}
          position={[0, 0.1, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1"
          castShadow
          receiveShadow
          geometry={nodes.object1.geometry}
          material={materials.Sandstone_Trim}
          position={[0, 0.1, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1001"
          castShadow
          receiveShadow
          geometry={nodes.object1001.geometry}
          material={materials.Sandstone_5}
          position={[-1, 0.1, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1006"
          castShadow
          receiveShadow
          geometry={nodes.object1006.geometry}
          material={materials["Sandstone_5.004"]}
          position={[-1, 0.1, 1.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1007"
          castShadow
          receiveShadow
          geometry={nodes.object1007.geometry}
          material={materials["Sandstone_5.005"]}
          position={[1, 0.1, -1.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1008"
          castShadow
          receiveShadow
          geometry={nodes.object1008.geometry}
          material={materials["Sandstone_5.006"]}
          position={[1, 0.1, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1009"
          castShadow
          receiveShadow
          geometry={nodes.object1009.geometry}
          material={materials["Sandstone_5.007"]}
          position={[1, 0.1, 0.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-1}
        />
        <mesh
          name="object1010"
          castShadow
          receiveShadow
          geometry={nodes.object1010.geometry}
          material={materials["Sandstone_5.008"]}
          position={[1, 0.1, 1.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name="object1011"
          castShadow
          receiveShadow
          geometry={nodes.object1011.geometry}
          material={materials["Sandstone_5.009"]}
          position={[-1, 0.1, -1.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-1}
        />
        <mesh
          name="object1012"
          castShadow
          receiveShadow
          geometry={nodes.object1012.geometry}
          material={materials["Sandstone_5.010"]}
          position={[-1, 0.1, -0.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name="object1019"
          castShadow
          receiveShadow
          geometry={nodes.object1019.geometry}
          material={materials["Sandstone_Floor.001"]}
          position={[0, 1.3, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          name="object1020"
          castShadow
          receiveShadow
          geometry={nodes.object1020.geometry}
          material={materials["Sandstone_5.011"]}
          position={[0, 0.2, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1021"
          castShadow
          receiveShadow
          geometry={nodes.object1021.geometry}
          material={materials["Sandstone_5.012"]}
          position={[0, 0.2, -1.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1023"
          castShadow
          receiveShadow
          geometry={nodes.object1023.geometry}
          material={materials["Sandstone_5.014"]}
          position={[1, 0.2, 1.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1026"
          castShadow
          receiveShadow
          geometry={nodes.object1026.geometry}
          material={materials["Sandstone_5.017"]}
          position={[1, 0.2, 0.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1022"
          castShadow
          receiveShadow
          geometry={nodes.object1022.geometry}
          material={materials["Sandstone_5.018"]}
          position={[-1, 0.2, -0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="object1024"
          castShadow
          receiveShadow
          geometry={nodes.object1024.geometry}
          material={materials["Sandstone_5.019"]}
          position={[-1, 0.2, -1.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="object1025"
          castShadow
          receiveShadow
          geometry={nodes.object1025.geometry}
          material={materials["Sandstone_5.020"]}
          position={[1, 0.2, -0.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name="object1027"
          castShadow
          receiveShadow
          geometry={nodes.object1027.geometry}
          material={materials["Sandstone_5.021"]}
          position={[-1, 0.2, 1.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name="object1028"
          castShadow
          receiveShadow
          geometry={nodes.object1028.geometry}
          material={materials["Sandstone_5.022"]}
          position={[1, 0.2, -1.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-1}
        />
        <mesh
          name="object1029"
          castShadow
          receiveShadow
          geometry={nodes.object1029.geometry}
          material={materials["Sandstone_5.023"]}
          position={[-1, 0.2, 0.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-1}
        />
      </group>
    </RigidBody>
  );
};

useGLTF.preload("/LibraryCorridor.glb");
