/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryMainRoom.glb -t -k -s -i 
Files: LibraryMainRoom.glb [322.88KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryMainRoom-transformed.glb [22.12KB] (93%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    object2: THREE.Mesh;
    object1006: THREE.Mesh;
    object1004: THREE.Mesh;
    object1009: THREE.Mesh;
    object1001: THREE.Mesh;
    object1026: THREE.Mesh;
    object1026_1: THREE.Mesh;
    object1027: THREE.Mesh;
    object1150: THREE.Mesh;
  };
  materials: {
    ["Sandstone_5.001"]: THREE.MeshStandardMaterial;
    ["Sandstone_Trim.003"]: THREE.MeshStandardMaterial;
    ["Sandstone_Floor.008"]: THREE.MeshStandardMaterial;
    ["Sandstone_4.002"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const LibraryMainRoom = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/LibraryMainRoom-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="object2"
        castShadow
        receiveShadow
        geometry={nodes.object2.geometry}
        material={materials["Sandstone_5.001"]}
        position={[0, 0.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1006"
        castShadow
        receiveShadow
        geometry={nodes.object1006.geometry}
        material={materials["Sandstone_Trim.003"]}
        position={[1, 0.1, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="object1004"
        castShadow
        receiveShadow
        geometry={nodes.object1004.geometry}
        material={materials["Sandstone_Floor.008"]}
        position={[0.5, 0.1, -0.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="object1009"
        castShadow
        receiveShadow
        geometry={nodes.object1009.geometry}
        material={nodes.object1009.material}
        position={[0, 1.1, -3.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="object1001"
        castShadow
        receiveShadow
        geometry={nodes.object1001.geometry}
        material={materials["Sandstone_4.002"]}
        position={[0.5, 0.15, -0.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 0.75]}
      />
      <instancedMesh
        args={[nodes.object1027.geometry, materials["Sandstone_5.001"], 8]}
        name="object1027"
        castShadow
        receiveShadow
        instanceMatrix={nodes.object1027.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1150.geometry, materials["Sandstone_5.001"], 8]}
        name="object1150"
        castShadow
        receiveShadow
        instanceMatrix={nodes.object1150.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1026.geometry, materials["Sandstone_Trim.003"], 8]}
        name="object1026"
        castShadow
        receiveShadow
        instanceMatrix={nodes.object1026.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.object1026_1.geometry, materials["Sandstone_5.001"], 8]}
        name="object1026_1"
        castShadow
        receiveShadow
        instanceMatrix={nodes.object1026_1.instanceMatrix}
      />
    </group>
  );
};

useGLTF.preload("/LibraryMainRoom-transformed.glb");
