/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridorDoors.glb -t -k -i -T 
Files: LibraryCorridorDoors.glb [9.51KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryCorridorDoors-transformed.glb [1.94KB] (80%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object2001: THREE.Mesh
  }
  materials: {
    ['Sandstone_5.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridorDoors-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object2001" geometry={nodes.object2001.geometry} material={materials['Sandstone_5.001']} position={[0, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridorDoors-transformed.glb')
