/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridorWalls.glb -t -k -i -T 
Files: LibraryCorridorWalls.glb [5.86KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryCorridorWalls-transformed.glb [3.61KB] (38%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1002: THREE.Mesh
    object1009: THREE.Mesh
  }
  materials: {
    floor: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridorWalls-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object1002" geometry={nodes.object1002.geometry} material={materials.floor} position={[0, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1009" geometry={nodes.object1009.geometry} material={'transparent'} position={[-2, 0.1, -0.9]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridorWalls-transformed.glb')
