/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridorNoColliders.glb -t -k -i -T 
Files: LibraryCorridorNoColliders.glb [54.1KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryCorridorNoColliders-transformed.glb [6.49KB] (88%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1002: THREE.Mesh
    object1009: THREE.Mesh
    object2001: THREE.Mesh
    object1001: THREE.Mesh
  }
  materials: {
    Sandstone_Floor: THREE.MeshStandardMaterial
    ['Sandstone_5.001']: THREE.MeshStandardMaterial
    ['Sandstone_Trim.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridorNoColliders-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object1002" geometry={nodes.object1002.geometry} material={materials.Sandstone_Floor} position={[0, 0.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1009" geometry={nodes.object1009.geometry} material={'transparent'} position={[-2, 0.1, -0.9]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object2001" geometry={nodes.object2001.geometry} material={materials['Sandstone_5.001']} position={[0, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1001" geometry={nodes.object1001.geometry} material={materials['Sandstone_Trim.002']} position={[0, 0.1, 0.1]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridorNoColliders-transformed.glb')
