/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LibraryCorridorNoColliders.glb -t -k -i -T 
Files: LibraryCorridorNoColliders.glb [47.54KB] > /home/tomoon/Documents/archiveOfBabel/public/LibraryCorridorNoColliders-transformed.glb [18.3KB] (62%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object1007: THREE.Mesh
    object1008: THREE.Mesh
    object1019: THREE.Mesh
    object1001: THREE.Mesh
  }
  materials: {
    ['Sandstone_5.005']: THREE.MeshStandardMaterial
    sandstonetrim: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LibraryCorridorNoColliders-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="object1007" geometry={nodes.object1007.geometry} material={materials['Sandstone_5.005']} position={[1, 0.1, -1.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="object1008" geometry={nodes.object1008.geometry} material={materials.sandstonetrim} position={[1, 0.1, -0.1]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="object1019" geometry={nodes.object1019.geometry} material={materials.floor} position={[0, 1.3, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh name="object1001" geometry={nodes.object1001.geometry} material={materials.wall} position={[0, 0.1, 0.1]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/LibraryCorridorNoColliders-transformed.glb')
